### ISSUE TITLE
Delete https://registry.hub.docker.com/u/patrickod/docker-tor/

### ISSUE THREAD

**Issue by ypid** [patrickod/docker-tor#11]
You have two images for tor on Docker Hub:

* https://registry.hub.docker.com/u/patrickod/tor/
* https://registry.hub.docker.com/u/patrickod/docker-tor/

I think you can delete the last one.

**Comment by patrickod** [comment]
:+1: thanks. will do :)

**Comment by patrickod** [comment]
Deleted. Thanks for the heads up.
